version: "2.15.1"
services:
  dateBuzz-database:
    container_name: dateBuzz-database
    build:
      dockerfile: Dockerfile
      context: ./database
    image: shoeone/datebuzz-database
    environment:
      - MARIADB_DATABASE=DateBuzz
      - MARIADB_ROOT_PASSWORD=${DATASOURCE_PASSWORD}
    volumes:
      - ./database/config:/etc/mysql/conf.d
    ports:
      - "3306:3306"
  dateBuzz-app:
    container_name: dateBuzz-app
    build: .
    depends_on:
      - dateBuzz-database
    image: shoeone/datebuzz-app
    environment:
      - SPRING_DATASOURCE_USERNAME=${DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DATASOURCE_PASSWORD}
      - SPRING_PROFILES_ACTIVE=${PROFILES_ACTIVE}
    ports:
      - "80:8080"
    restart: always
