
spring:
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
  data:
    redis:
      url:
  mvc:
    decodeCharset: UTF-8
    urlEncoding:
      charset: UTF-8
jwt:
  secret-key: ${TOKEN_SECRET_KEY}
  token:
    expired-time-ms: ${TOKEN_EXPIRE_TIME}
cloud:
  aws:
    credentials:
      accessKey: ${CLOUD_ACCESS_KEY}
      secretKey: ${CLOUD_SECRET_KEY}
    region:
      static: ap-northeast-2
    s3:
      bucket: datebuzz-bucket
bot:
  token: ${BOT_TOKEN}
  username: ${BOT_USER_NAME}
  chatId: ${BOT_CHAT_ID}
