# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Overwrite application.yaml with Secrets
      run: |
        cd ./Back-end
            echo 
        "spring:
          datasource:
            url: \${{ secrets.DATASOURCE_URL }}
            username: \${{ secrets.DATASOURCE_USERNAME }}
            password: \${{ secrets.DATASOURCE_PASSWORD }}
            driver-class-name: org.mariadb.jdbc.Driver
          jpa:
            hibernate:
              ddl-auto: update
            properties:
              hibernate:
                #show_sql: true
                format_sql: true
          data:
            redis:
              url:
          mvc:
            decodeCharset: UTF-8
            urlEncoding:
              charset: UTF-8
        jwt:
          secret-key: \${{ secrets.TOKEN_SECRET_KEY }}
          token:
            expired-time-ms: \${{ secrets.TOKEN_EXPIRE_TIME }}
        cloud:
          aws:
            credentials:
              accessKey: \${{ secrets.CLOUD_ACCESS_KEY }}
              secretKey: \${{ secrets.CLOUD_SECRET_KEY }}
            region:
              static: ap-northeast-2
            s3:
              bucket: datebuzz-bucket
        bot:
          token: \${{ secrets.BOT_TOKEN }}
          username: \${{ secrets.BOT_USER_NAME }}
          chatId: \${{ secrets.BOT_CHAT_ID }}" > ./src/main/resources/application.yaml
      
    - name: Install Gradle
      run: |
        cd ./Back-end
        wget https://services.gradle.org/distributions/gradle-7.6.1-bin.zip
        unzip -d $HOME/gradle gradle-7.6.1-bin.zip
        echo "export PATH=\$HOME/gradle/gradle-7.6.1/bin:\$PATH" >> $HOME/.bashrc
        source $HOME/.bashrc

    - name: Build with Gradle
      run: |
        cd ./Back-end
        gradle clean build

      
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        
    - name: Build and push Docker image
      run: |
        cd ./Back-end
        docker build -t dateBuzz/dateBuzzExecute .
        docker push dateBuzz/dateBuzzExecute
        
    - name: SSH and Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.REMOTE_SSH_KEY }}
        script: |
          docker stop dateBuzzExecute || true
          docker rm dateBuzzExecute || true
          docker pull dateBuzz/dateBuzzExecute
          docker run -d -p 8080:8080 --name dateBuzzExecute dateBuzz/dateBuzzExecute
